### ISSUE TITLE
Change "Reply to" on emails received to info@ email account from the website contact form

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#19]
When receiving emails to the info@ email account from the contact form, the from/reply to email is matt@sdrefugeetutoring.com 

So when hitting reply to the original email, the email address is matt@refugeetutoring.com instead of the email address of the person who filled out the contact form.

At one point, the "reply to" email address used to be the email address that was entered into the contact form. Can that be changed back? 

Attached is a screenshot for reference. 
![Screenshot_20190805-145152](https://user-images.githubusercontent.com/47679296/62513272-4c23b580-b7d0-11e9-8e93-0c092100ce12.png)

**Comment by mathetos** [comment]
I believe this is resolved.

**Comment by dreazee** [comment]
@mathetos I never saw your comment on this issue. It hasn't been resolved, though

**Comment by mathetos** [comment]
@dreazee I double-checked the form settings again. It's pulling the "Reply to" from the users email address field correctly. See here:

![image](https://user-images.githubusercontent.com/930724/73504512-7cfe3500-4384-11ea-803b-370f3a2af082.png)

**Comment by dreazee** [comment]
@matheos Here's a screenshot of what I see when I hit reply on this
contract form emails. Saying the email is from you -
matt@sdrefugeetutoring.com - and replying to you.

**Comment by dreazee** [comment]
@mathetos I see that the form settings were doubled-checked, but just so you know, this issue still persists. Please see the screenshot attached. 

![Screenshot_20200707-082920](https://user-images.githubusercontent.com/47679296/86856300-e93a3e80-c070-11ea-8854-ab6f888a9119.png)


> @dreazee I double-checked the form settings again. It's pulling the "Reply to" from the users email address field correctly. See here:
> 
> ![image](https://user-images.githubusercontent.com/930724/73504512-7cfe3500-4384-11ea-803b-370f3a2af082.png)
