### ISSUE TITLE
[MEGA SUPER HIGH] Issue submitting Registration Form (for some people!)

### ISSUE THREAD

**Issue by dreazee** [SDRefugeeTutoring/sdrt-custom-functions#61]
A User emailed about this issue yesterday at 4:30 p.m. When trying to Register, the page just continues to load and will not submit the form. I chalked it up to User error since **info@ has received other "New User" notification emails in the interim,** even one as early as this morning.
However, I was able to replicate the issue when I tried to Register for the User this morning <see screenshot below>. 
I tried on Windows 10 OS using Firefox and Chrome browsers and tested using different DOBs, email addresses, etc. I was not logged in to SDRT website when testing. Still unsuccessful.
The User was using a cell phone. 

The Caldera Registration Form *was* edited yesterday, but don't see how that would make it impossible for a few users to not be able to submit the form and other users to be able to. The edits made:
1. Made 5 & 6 questions required
2. Changed wording of 6th question

![Registration Form](https://user-images.githubusercontent.com/47679296/135328650-c7ec9944-e9a5-4563-a70a-d2280da2e020.png)

**Comment by dreazee** [comment]
@JasonTheAdams More people are reporting issues with the Registration Form not submitting. How is the migration to Gravity Forms looking?

**Comment by JasonTheAdams** [comment]
I'm 95% finished with this. I just need to update a few things on production and then push the new code. I'm aiming to take this live this evening.

**Comment by dreazee** [comment]
GREAT NEWS. KEEP ME POSTED!!!

**Comment by JasonTheAdams** [comment]
Hi @dreazee!

Ok! I just pushed the new changes live. This took me a bit, but I put a lot of extra work into this to get us ready for migrating more of the forms, as well as starting to make general improvements to the codebase. Since this is so important, I did my best to test this out of the Dev environment, using the testing version of Checkr. It all worked for me. Nevertheless, please test this with a person as soon as you're able!

One quick improvement I thought of, but I wanted to get your thoughts on: On the Volunteer Registration page, when the user registers it reloads the page and replaces the form with the following text:
```
Hi {Name (First):1.3},

Thank you for registering with San Diego Refugee Tutoring! To finish your registration, please verify your email. You have been sent an email, simply click on the link provided in your email. You will then be provided with the steps to complete your background check.
```

Since the text on the page is so long it's pretty easy to not notice this, however. I thought about making a new page to send the user to so the content is very clear. So when the user submits the form it redirects them to the new page with instructions. But I wasn't sure if for some reason you wanted the user to stay on the volunteer page?

**Comment by dreazee** [comment]
Awesome about the new changes!! I'm excited to test them out!!

However, I thought a User wasn't going to need to verify their email address? And that a User would be "approved" automatically without anything else to do on a User side or Admin side... ?

**Comment by JasonTheAdams** [comment]
I know it seems the same, but it's actually not doing that. The user isn't providing a password at the time of registration, so they get an email to be able to log in and set an email. The new user is immediately registered with Checkr though. So even if they don't follow the link to log in, they will still get the Checkr email to go through the background check.

**Comment by dreazee** [comment]
Okay, cool. It is a good idea for the User to still be on the Volunteer Registration page. BUT I don't see any issue with them being sent to a NEW TAB where the information is. So then the User will still have the previous tab with the Volunteer Registration page open and then the new tab with this information that is important.

**Comment by JasonTheAdams** [comment]
I adjusted it so that when the form is submitted it doesn't reload the page, so the user's scroll position is held and they'll see the resulting message. I'm happy with this as it keeps them on the registration page and shows them the immediate message. I'm going to call this a success. 🎉
